baseURL = 'https://nibsi.online/'
languageCode = 'en-us'
title = 'nibsi.online'
theme = 'anubis'
paginate = 3

disqusShortname = "nibsi-online"
googleAnalytics = "G-H0LECCQNPF"
googleAnalyticsID = "G-H0LECCQNPF"


[author]
name = "Nico Hämäläinen"

[params]
author = "Nico Hämäläinen"
description = "."
dateFormat = "01-12-2023"
paginationSinglePost = true
style = "auto"
readMore = false
readNextPosts = 2
copyCodeButton = true
rssAsSocialIcon = true

# Graphcomment support
graphcommentId = ""

# utteranc.es support
utterancesRepo = ""  # mandatory
utterancesTheme = "" # optional
utterancesIssue = "" # optional
utterancesLabel = "" # optional

[[params.social]]
id = "docs"
url = "https://gohugo.io/documentation/"

[[params.social]]
id = "github"
url = "https://github.com/mitrichius/hugo-theme-anubis"

[menu]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
name = "Archive"
identifier = "archive"
url = "/posts/"
weight = 3

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true
